server:
  port: 9000

spring:
  application:
    name: ad-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

zuul:
  prefix: /daijizai
  routes:
    sponsor:
      path: /ad-sponsor/**
      serviceId: eureka-client-ad-sponsor
      strip-prefix: false
    search:
      path: /ad-search/**
      serviceId: eureka-client-ad-search
      strip-prefix: false
    page:
      path: /ad-page/**
      serviceId: eureka-client-ad-page
      strip-prefix: false